image: docker:git
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay

before_script:
  - if [[ $CI_BUILD_REF_NAME == "master" ]]; then DOCKER_IMAGE=$CI_REGISTRY_IMAGE:test; else DOCKER_IMAGE=$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME; fi

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - master
    - staging
    - production