[template]
prefix = "/self/service/metadata"
src = "traefik.key.tmpl"
dest = "/opt/traefik/certs/traefik.key"
owner = "traefik"
mode = "0600"
keys = [
  "/traefik",
]

reload_cmd = "/opt/traefik/bin/traefik-service.sh restart"